<?php
/** @var Paynow\PaymentGateway\Block\Order\History\Action $block */
/** @var Magento\Sales\Model\Order $order */
$order = $block->getData('order');
if ($order !== null) :
    if ($block->canRetryPayment($order->getEntityId())) : ?>
        <a href="<?= $block->escapeUrl($block->getRetryPaymentUrl($order->getEntityId())); ?>" class="action order">
            <span><?= $block->escapeHtml(__('Retry payment')); ?></span>
        </a>
        <?php
    endif;
endif;
