<?php
/** @var Paynow\PaymentGateway\Block\Payment\Confirm $block */
?>
<div data-bind="scope: 'confirm'" class="paynow-confirm-blik">
    <p class="headline"><?= $block->escapeHtml(__('Confirm the payment using the app on your phone.')) ?></p>
    <img src="<?= $block->escapeUrl($block->getConfirmBlikImageUrl()); ?>" alt="">
    <div>
        <p>
            <?= $block->escapeHtml(__('Your payment ID: ')) ?>
            <span data-bind="text: paymentId">
                <?= $block->escapeHtml($block->getPaymentId()) ?>
            </span>
        </p>
        <p>
            <?= $block->escapeHtml(__('Current payment status: ')) ?>
            <span class="status" data-bind="text: paymentStatusLabel">
                <?= $block->escapeHtml($block->getPaymentStatusLabel()); ?>
            </span>
        </p>
    </div>
</div>

<script type="text/x-magento-init">
{
    "*": {
        "Magento_Ui/js/core/app": {
            "components": {
                "confirm": {
                    "component": "Paynow_PaymentGateway/js/view/payment/paynow_confirm_blik",
                    "paymentStatus": "<?= /* @noEscape */ $block->getPaymentStatus() ?>",
                    "paymentStatusLabel": "<?= /* @noEscape */ $block->getPaymentStatusLabel() ?>",
                    "paymentId": "<?= /* @noEscape */ $block->getPaymentId() ?>"
                }
            }
        }
    }
}
</script>
