<?php
/** @var Paynow\PaymentGateway\Block\Onepage\Success $block */
/** @var Magento\Sales\Model\Order $order */
if ($order !== null) : ?>
    <p><?= $block->escapeHtml($block->getPaymentStatusPhrase()); ?></p>
    <?php if ($block->canRetryPayment()) : ?>
        <p><?=$block->escapeHtml(__('Use the button below to retry payment')); ?></p>
        <div class="primary">
            <a class="action primary continue" href="<?= $block->escapeUrl($block->getRetryPaymentUrl($order)); ?>">
                <span><?= $block->escapeHtml(__('Retry payment')); ?></span>
            </a>
        </div>
        <br/>
        <?php
    endif;
endif;
